### ISSUE TITLE
Preview is weirdly indented

### ISSUE THREAD

**Issue by RefusesNames** [LoricAndre/fzterm.nvim#10]
As you can see here, the content of the preview pane is weirdly indented:
![image](https://user-images.githubusercontent.com/823148/97959197-198bb280-1daf-11eb-83be-68613191ba06.png)
That's a lot of lost space considering that the file shown in the picture does not even include indentation.

**Comment by LoricAndre** [comment]
Hi,
this is linked to the way `bat` displays files, what you see on the left isn't completely blank but you can faintly see some line numbers. I reduced it with the last push (displaying only line numbers and not the frame), can you try it out ? Unfortunately, I can't reduce the margin further on my end, so you might have to use cat instead of bat and lose the syntax highlighting... You can ask for more details on how to do that here if you need.
